Cargo.lock, Cargo.toml, src/clap/camino.rs, src/clap/error_message.rs, src/clap/humantime.rs, src/clap/mod.rs, src/cli.rs, src/main.rs, src/watcher.rs
This adds a user-tunable `--debounce` option and a `--poll` option.
=> Implement `--debounce` and `--poll`

src/clap/camino.rs, src/clap/humantime.rs, src/clap/mod.rs, src/cli.rs, src/ghci/mod.rs, src/ghci/stderr.rs, src/ghci/stdin.rs, src/ghci/stdout.rs, src/main.rs, src/watcher.rs
This writes stderr to an output file, clearing it between reloads.
=> Implement `--errors` for `ghcid.txt`

Cargo.toml
`package.metadata.release.dev-version` no longer exists.
=> Fix `cargo release`

Cargo.lock, Cargo.toml, flake.nix
Update version to 0.1.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.1.1

Cargo.lock, Cargo.toml, src/ghci/stderr.rs
This should make it easier to view `ghcid.txt` in a text editor.
=> Strip ANSI escapes when writing `ghcid.txt`

Cargo.lock, Cargo.toml, src/ghci/mod.rs, src/ghci/stderr.rs, src/ghci/stdin.rs, src/ghci/stdout.rs, src/main.rs
This will actually log errors using `tracing::error!`. No more silent errors!
The `backoff` crate does claim to support futures, but I couldn't get it to work with my functions. Something about calling an `&mut self` function, I think? Anyways, I can at least use their exponential backoff implementation, which is quite nice: it supports duration caps on both individual retry attempts and the total elapsed time, adjustable jitter, and fractional exponents.
I'm not in love with the boilerplate duplicated between the three main tasks, but it may have to do.
If I try to copy the [`backoff` async example](https://github.com/ihrwein/backoff/blob/master/examples/async.rs) like so:
```rust
backoff::future::retry(ExponentialBackoff::default(), || async move {
match self.run_inner().await {
Ok(()) …
```
=> Log errors in async tasks

Cargo.lock, Cargo.toml, src/cli.rs, src/ghci/mod.rs, src/ghci/stderr.rs, src/ghci/stdin.rs, src/ghci/stdout.rs, src/incremental_reader.rs, src/main.rs
This adds `--test` and `--setup` arguments which can be used to run a test suite on reload.
=> Run tests on save

Cargo.lock, Cargo.toml, flake.nix
Update version to 0.2.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.2.0

src/ghci/mod.rs, src/ghci/stderr.rs, src/ghci/stdin.rs, src/ghci/stdout.rs
This was the intended behavior in #11, but I got the booleans backwards. Don't worry, tests are next on the roadmap...
=> Don't run tests when compilation fails

Cargo.lock, Cargo.toml, flake.nix
Update version to 0.2.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.2.1

Cargo.lock, Cargo.toml, flake.nix
Update version to 0.2.2 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.2.2

src/ghci/mod.rs, src/watcher.rs
In #11 I removed the `Weak<Ghci>` pointers from the ghci task structs, favoring the `mpsc` channels for communication over locking a mutex. This means I can make several simplifications, in particular turning `Ghci::reload` into a real method that uses `std::mem::replace`.
=> Move `Ghci` out of the `Arc<Mutex<_>>`

src/clap/fmt_span.rs, src/clap/mod.rs, src/cli.rs, src/main.rs, src/tracing/mod.rs
Currently, new/close span events are logged (that is, when a span is created for the first time, usually when an `#[instrument]`ed function is called, and when spans are closed, usually when those functions return). It can be useful to disable those for terser logs, or to enable more events for greater detail.
This change adds a `--trace-spans` argument to customize which span events are logged.
Before shipping 1.0, we should clean up the option names. Maybe `--tracing-filter` could be `--log` or something.
=> Allow customizing logged span events

src/ghci/mod.rs, src/ghci/stdin.rs
This removes the process that manages `GhciStdin` and instead replaces the handle to that process with the `GhciStdin` struct.
The motivation behind this change is to remove the need for a `StdinEvent` type and avoid the need to spawn and monitor/restart a process.  This also simplifies method invocations on that process, too.
=> Remove `GhciStdin` process

Cargo.lock, Cargo.toml, flake.nix
Update version to 0.3.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.0

.github/workflows/version.yaml, flake.lock, flake.nix, src/fake_reader.rs, src/ghci/mod.rs
[Crane](https://crane.dev/) is a Nix framework for building Rust packages. The main benefit is that it separates the build of the dependency packages into a separate derivation, so that those artifacts can be reused between builds and CI runs.
=> Use crane for Nix builds

flake.nix, ghcid-ng/tests/data/simple/simple.cabal, ghcid-ng/tests/data/simple/src/MyLib.hs, ghcid-ng/tests/data/simple/src/MyModule.hs, ghcid-ng/tests/data/simple/test/Main.hs
Adds a simple Haskell project to the test data.
We will load this project in `ghci` to test `ghcid-ng`.
=> Add test Haskell project

Cargo.lock, test-harness/Cargo.toml, test-harness/src/lib.rs, test-harness/src/tracing_json.rs, test-harness/src/tracing_reader.rs
The Tracing JSON reader is an async task which will wait for `ghcid-ng` to write tracing log events to a file, deserialize them, and make them available to the test harness.
This is the core of the tests; `ghcid-ng` is started, we wait for a particular log event, we make changes with the IO helpers, repeat.
=> Add tracing JSON reader to test-harness

Cargo.lock, test-harness/Cargo.toml, test-harness/src/lib.rs, test-harness/src/matcher.rs, test-harness/src/tracing_json.rs
The event matcher is an API which test authors can use to request that the test waits until a certain log message is seen. Logs can be matched based on the spans they're contained in, the module they originated from, and a regular expression match on the log message.
=> Add tracing event matcher to test-harness

Cargo.lock, Cargo.toml, flake.nix, test-harness-macro/Cargo.toml, test-harness-macro/src/lib.rs, test-harness/Cargo.toml, test-harness/src/fs.rs, test-harness/src/ghcid_ng.rs, test-harness/src/internal.rs, test-harness/src/lib.rs, test-harness/src/matcher.rs, test-harness/src/tracing_json.rs, test-harness/src/tracing_reader.rs
The `GhcidNg` type copies a given directory to a tempdir and then launches `ghcid-ng` there. It also spawns an async task to read JSON log events from the log file.
`GhcidNg` uses thread-local storage to determine which version of `ghc` to use when launching tests, and will error appropriately if the thread-local storage is not set. This takes advantage of the fact that async tests run in the `tokio` "current-thread" runtime by default, which schedules all tasks in the test on the same thread.
The second part is a proc macro attribute exported as `#[test_harness::test]`, which rewrites tests so that
1. The tests are async functions which run under the default `#[tokio::test]` current-thread runtime.
2. Tracing is set up in the tests so that log messages from the `test-harness` library are …
=> Add test harness

ghcid-ng/src/clap/clonable_command.rs, ghcid-ng/src/clap/mod.rs, ghcid-ng/src/cli.rs, ghcid-ng/src/command.rs, ghcid-ng/src/ghci/mod.rs, ghcid-ng/src/ghci/stdin.rs, ghcid-ng/src/main.rs, ghcid-ng/src/tracing/mod.rs, ghcid-ng/src/watcher.rs, ghcid-ng/tests/test.rs
This parses shell command arguments into a new `ClonableCommand` struct, which stores the program, arguments, and environment for a command to be run.
I've also converted several of the more complex constructors into accepting structs instead of multiple positional arguments, which get challenging to track.
=> Parse shell command arguments

Cargo.lock, ghcid-ng/tests/error_log.rs, ghcid-ng/tests/test.rs, test-harness/Cargo.toml, test-harness/src/ghcid_ng.rs, test-harness/src/lib.rs, test-harness/src/matcher.rs
This lets tests run code to modify the project before starting `ghcid-ng`.
The before-start hook is implemented in terms of a new `GhcidNgBuilder` interface.
=> Add before-start hook to the test harness

Cargo.lock, ghcid-ng/Cargo.toml, ghcid-ng/src/ghci/parse/module_set.rs, ghcid-ng/src/ghci/stdout.rs, ghcid-ng/src/incremental_reader.rs
This is conceptually somewhat simpler and also gives us output that's easier to feed to parsers.
=> Make `IncrementalReader` return strings, not lists of lines

ghcid-ng/src/ghci/mod.rs, ghcid-ng/src/ghci/parse/ghc_message/cant_find_file_diagnostic.rs, ghcid-ng/src/ghci/parse/ghc_message/compilation_summary.rs, ghcid-ng/src/ghci/parse/ghc_message/compiling.rs, ghcid-ng/src/ghci/parse/ghc_message/generic_diagnostic.rs, ghcid-ng/src/ghci/parse/ghc_message/loaded_configuration.rs, ghcid-ng/src/ghci/parse/ghc_message/message_body.rs, ghcid-ng/src/ghci/parse/ghc_message/mod.rs, ghcid-ng/src/ghci/parse/ghc_message/module_import_cycle_diagnostic.rs, ghcid-ng/src/ghci/parse/ghc_message/no_location_info_diagnostic.rs, ghcid-ng/src/ghci/parse/ghc_message/path_colon.rs, ghcid-ng/src/ghci/parse/ghc_message/position.rs, ghcid-ng/src/ghci/parse/ghc_message/severity.rs, ghcid-ng/src/ghci/parse/ghc_message/single_quote.rs, ghcid-ng/src/ghci/parse/lines.rs, ghcid-ng/src/ghci/parse/mod.rs, ghcid-ng/src/ghci/parse/module_set.rs, ghcid-ng/src/ghci/stderr.rs, ghcid-ng/src/ghci/stdin.rs, ghcid-ng/src/ghci/stdout.rs, ghcid-ng/src/incremental_reader.rs, ghcid-ng/tests/basic.rs, ghcid-ng/tests/error_log.rs, ghcid-ng/tests/failed_modules.rs, test-harness/src/ghcid_ng.rs, test-harness/src/internal.rs, test-harness/src/tracing_reader.rs
This parses GHC diagnostics and uses the output to avoid `:add`ing failed modules. See the bug upstream here: https://gitlab.haskell.org/ghc/ghc/-/issues/13254
=> Fix "module defined in multiple files" by parsing GHC diagnostics

.github/labeler.yml, test-harness-macro/Cargo.toml, test-harness/Cargo.toml
This lets us label PRs as patch when they change source files.
=> Fix branch labeler

Cargo.lock, Cargo.toml
Update version to 0.3.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.1

Cargo.lock, Cargo.toml, src/ghci/error_log.rs, src/ghci/mod.rs, src/ghci/parse/ghc_message/cant_find_file_diagnostic.rs, src/ghci/parse/ghc_message/compilation_summary.rs, src/ghci/parse/ghc_message/generic_diagnostic.rs, src/ghci/parse/ghc_message/message_body.rs, src/ghci/parse/ghc_message/mod.rs, src/ghci/parse/ghc_message/module_import_cycle_diagnostic.rs, src/ghci/parse/ghc_message/no_location_info_diagnostic.rs, src/ghci/parse/ghc_message/position.rs, src/ghci/parse/ghc_message/severity.rs, src/ghci/parse/mod.rs, src/ghci/stderr.rs, src/ghci/stdout.rs, test-harness/src/matcher.rs, tests/error_log.rs, tests/test.rs
The biggest user-facing change here is to replace the `Ok, 123 modules loaded.` "compilation summary" headline with `All good (123 modules)`; [the `ghcid` editor plugins are hard-coded to recognize this string.](https://github.com/ndmitchell/ghcid/blob/e2852979aa644c8fed92d46ab529d2c6c1c62b59/plugins/vscode/src/extension.ts#L79)
Previously, I had a rather clever system for the error log which would direct anything on stderr to the error log, divided up by what it was doing; a separate section for test output and compiler output. This is of dubious utility -- anyone who wants to see the test output can just look at the console, so the `--errors` output should be for tooling only. In the future, it might be nice to experiment with getting test failures in there too -- maybe we could …
=> Make `--errors` output compatible with `ghcid`

Cargo.lock, Cargo.toml
Update version to 0.3.2 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.2

Cargo.lock, Cargo.toml
Update version to 0.3.3 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.3

Cargo.lock, Cargo.toml, src/cli.rs, src/ghci/ghci_command.rs, src/ghci/mod.rs, src/ghci/stdin.rs, tests/hooks.rs
This adds support for multiple test commands (`--test-ghci`) and before/after reload/restart hooks: `--before-reload-ghci`, `--after-reload-ghci`, `--before-restart-ghci`, and `--after-restart-ghci`. We may also consider before/after hooks for eval commands.
=> More lifecycle hooks

Cargo.lock, Cargo.toml
Update version to 0.3.4 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.4

src/ghci/mod.rs, src/ghci/stderr.rs, src/watcher.rs
Note that this won't gracefully exit until a reload is triggered, though.
=> Gracefully exit when `ghci` exits

Cargo.lock, Cargo.toml
Update version to 0.3.5 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.5

src/aho_corasick.rs, src/ghci/mod.rs, src/ghci/stdin.rs, src/ghci/stdout.rs, src/incremental_reader.rs, tests/dot_ghci.rs
Previously, `:set prompt` commands in `.ghci` configuration files would cause `ghcid-ng` to hang on start. This fixes that bug.
=> Allow custom prompts in `.ghci`

Cargo.lock, Cargo.toml
Update version to 0.3.6 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.6

src/command.rs, src/ghci/parse/module_set.rs, src/lib.rs, src/lines.rs, src/main.rs
This gives us better dead code warnings, among other things.
=> Housekeeping: Make most modules private

src/ghci/mod.rs, src/ghci/parse/show_paths.rs, src/ghci/stdin.rs, tests/rename.rs
This fixes a "modules defined in multiple files" bug when a module is renamed. The rename is interpreted as one module being deleted (which triggers a restart) and one module being added (which triggers an `:add`).
The bug is that it would restart `ghci`, thereby loading the new module, and then attempt to `:add` the new module anyways, which would fail.
=> Fix "modules defined in multiple files" bug when modules are renamed

Cargo.lock, Cargo.toml
Update version to 0.3.7 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.7

Cargo.lock, Cargo.toml
Update version to 0.3.8 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.8

src/event_filter.rs, src/normal_path.rs, test-harness/src/checkpoint.rs, test-harness/src/ghciwatch.rs, test-harness/src/internal.rs, test-harness/src/lib.rs, test-harness/src/matcher/and_matcher.rs, test-harness/src/matcher/base_matcher.rs, test-harness/src/matcher/fused_matcher.rs, test-harness/src/matcher/into_matcher.rs, test-harness/src/matcher/mod.rs, test-harness/src/matcher/negative_matcher.rs, test-harness/src/matcher/never_matcher.rs, test-harness/src/matcher/option_matcher.rs, test-harness/src/matcher/or_matcher.rs, tests/error_log.rs, tests/eval.rs, tests/failed_modules.rs, tests/hooks.rs, tests/reload.rs, tests/rename.rs, tests/restart.rs, tests/test.rs
These matcher combinators will let us express more complex logging concepts, like:
- Match these two events in any order.
- Match either of these two events.
- Match either of these two events, as long as this other event doesn't match first.
There's also a system of checkpoints where log events are read into the default checkpoint. At any time, you can create another checkpoint with `GhciWatch::checkpoint`. Then, log events will be read into the new checkpoint. Later, you can assert that messages were logged in a particular checkpoint or range of checkpoints.
=> Add matcher combinators

src/buffers.rs, src/fake_reader.rs, src/incremental_reader.rs
When we read from stdout, we get some number of bytes. In some cases, when `ghci` is outputting non-ASCII characters, this can lead to a single UTF-8 codepoint (represented as multiple bytes) being split across two reads. (Or potentially more, in perverse cases?)
Fortunately, the `std` UTF-8 decoder makes this information available and allows us to distinguish between truncated continuation sequences and truly invalid data. For truncated continuation sequences, we decode as much as we can (fortunately the `std` UTF-8 decoder makes this information available as well) and save the last few bytes (we know there are only 1-3 of them) for the next time we read data.
=> Fix error when reading from stdout splits UTF-8 codepoint

.config/nextest.toml, Cargo.lock, Cargo.toml, README.md, src/command_ext.rs, src/event_filter.rs, src/ghci/manager.rs, src/ghci/mod.rs, src/ghci/process.rs, src/ghci/stderr.rs, src/ghci/stdin.rs, src/ghci/stdout.rs, src/incremental_reader.rs, src/lib.rs, src/main.rs, src/normal_path.rs, src/shutdown.rs, src/watcher.rs, test-harness/src/fs.rs, test-harness/src/ghciwatch.rs, test-harness/src/internal.rs, test-harness/src/lib.rs, test-harness/src/matcher/base_matcher.rs, tests/data/simple/Makefile, tests/eval.rs, tests/reload.rs, tests/shutdown.rs
This PR switches `ghcid-ng` from the `watchexec` crate to using the `notify` crate directly. (This is what `watchexec` uses under the hood.) `watchexec` is very nice, but it's largely designed around the needs of the `watchexec(1)` binary (namely running commands when files change). Using `notify` makes the code much nicer.
One of the things that `watchexec` provides that `notify` doesn't is shutting down when Ctrl-C is pressed. Most of the rest of the changes are about implementing this graceful shutdown procedure.
See [the “Graceful Shutdown” section in the Tokio book](https://tokio.rs/tokio/topics/shutdown) for more details.
Originally I implemented this with [the `tokio-graceful-shutdown` crate](https://docs.rs/tokio-graceful-shutdown/latest/tokio_graceful_shutdown/), but it turned …
=> Graceful shutdown

Cargo.lock, Cargo.toml
Update version to 0.3.10 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.3.10

src/ghci/mod.rs
Will make debugging a bit easier.
=> Include file name in "failed to parse eval commands" error message

Cargo.lock, Cargo.toml
Update version to 0.4.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.4.1

src/ghci/parse/eval.rs, src/ghci/parse/lines.rs
With an eval command at the end of the file and no newline at the end of the file, parsing fails.
This happens because [VS Code is a bad text editor](https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files) that doesn't respect [POSIX](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline), which defines a line as:
> **3.206 Line**
> 
> A sequence of zero or more non- \<newline> characters plus a terminating \<newline> character.
No terminating newline? Not a line.
Anyways, we have to work around this because people aren't exactly going to stop using VS Code.
=> Parse eval commands when they end with EOF instead of a newline

Cargo.lock, Cargo.toml
Update version to 0.4.2 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.4.2

src/cli.rs, src/clonable_command.rs, src/command_ext.rs, src/ghci/mod.rs, src/lib.rs, src/maybe_async_command.rs, test-harness/src/fs.rs, test-harness/src/ghciwatch.rs, tests/hooks.rs
This lets you prefix shell commands with `async:` to have them run asynchronously. This will let us do things like reindex hie files in the background.
=> Support `async:` commands

Cargo.lock, Cargo.toml
Update version to 0.4.3 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.4.3

test-harness/src/fs.rs, test-harness/src/ghciwatch.rs, test-harness/src/lib.rs, tests/dot_ghci.rs, tests/error_log.rs, tests/eval.rs, tests/failed_modules.rs, tests/globs.rs, tests/hooks.rs, tests/load.rs, tests/reload.rs, tests/rename.rs, tests/restart.rs, tests/test.rs
The test suite features a load-bearing sleep of 1 second before writing. This makes the filesystem events get detected more reliably, for whatever reason.
This change allows disabling the load-bearing sleeps; this is typically needed to make several writes that all get detected together by `ghciwatch`.
=> Allow customizing load-bearing sleeps

src/command_ext.rs, src/event_filter.rs, src/ghci/manager.rs, src/ghci/mod.rs
This will give a snappier UX in general.
Note that now, many hooks can be canceled or mismatched (e.g. the before-reload hooks can run but the after-reload hooks get canceled). I'm not sure if this will cause issues with Honeycomb (e.g. spans that open but don't close).
=> Interrupt reloads when new files change

Cargo.lock, Cargo.toml
Update version to 0.5.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.0

Cargo.lock, Cargo.toml, src/cli.rs, src/ghci/mod.rs, src/ghci/parse/haskell_grammar.rs, src/ghci/stdin.rs, src/hooks.rs, src/lib.rs
Instead of having a field for each event (`before_restart_ghci`, `test_ghci`, `after_startup_shell`, etc.), we generate and store the arguments dynamically. This simplifies the running of hooks and will hopefully make it easier to extend the lifecycle hooks in the future.
=> Store lifecycle hooks dynamically

Cargo.lock, Cargo.toml
Update version to 0.5.2 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.2

src/ghci/mod.rs, test-harness/src/matcher/base_matcher.rs, tests/all_good.rs, tests/error_log.rs, tests/failed_modules.rs, tests/test.rs
Turned out I wasn't ever setting the "compilation failed" variable where I expected it.
Also I had a bug with the `BaseMatcher`, so I fixed it to be stricter about spans.
=> Don't print "All good!" when compilation is not "All good!"

Cargo.lock, Cargo.toml
Update version to 0.5.4 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.4

src/ghci/mod.rs, src/hooks.rs, src/lib.rs, src/string_case.rs, test-harness/src/matcher/base_matcher.rs
Make the "compilation failed" message error-level rather than debug-level. The `ghci` error output does generally show when compilation fails, but without a visible prompt it's not super clear when exactly compilation finished. This is a follow-up to #167 + #170, which added an "All good!" message.
=> Make the compilation failed message visible

Cargo.lock, Cargo.toml
Update version to 0.5.5 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.5

src/ghci/mod.rs, src/main.rs, src/shutdown.rs
Their `spawn` methods are usually invoked with string literals (`&str`), so it's nicer to do the conversion to an owned string internally.
I used `impl Into<String>` instead of `&str` to ensure we don't re-allocate if we already have a `String`.
=> Let `Shutdown{Manager,Handle}::spawn` take `&str`

Cargo.lock, Cargo.toml
Update version to 0.5.6 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.6

src/ghci/mod.rs, src/maybe_async_command.rs, test-harness/src/ghciwatch.rs, test-harness/src/lib.rs, test-harness/src/matcher/base_matcher.rs, test-harness/src/matcher/field_matcher.rs, test-harness/src/matcher/mod.rs, test-harness/src/matcher/span_matcher.rs, test-harness/src/tracing_json.rs, tests/hooks.rs
This lets users observe error log output in lifecycle hooks. Useful for some editor integrations, e.g.:
```
vim --servername $VIM_SERVERNAME --remote-send "<C-W>:cgetfile ghcid.txt<CR>"
```
Also adds a couple features to the test harness:
- Extra tracing filters (`--tracing-filter`) can be added in tests
- Span fields can now be matched as well as names
=> Write `--errors` log before running shell hooks

Cargo.lock, Cargo.toml
Update version to 0.5.7 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.7

Cargo.lock, Cargo.toml, src/cli.rs, src/ghci/mod.rs, tests/clear.rs, tests/restart.rs
It's possible to hack around this with lifecycle hooks:
```shell
ghciwatch \
--before-startup-shell 'sh -c "clear >/dev/tty"' \
--before-reload-shell 'sh -c "clear >/dev/tty"' \
--before-restart-shell 'sh -c "clear >/dev/tty"'
```
But it's nice to have a baked option for it.
=> Clear the screen on reload with `--clear`

Cargo.lock, Cargo.toml
Update version to 0.5.8 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.8

src/tui/mod.rs
Adds a bunch of Vim/`less`-like key bindings I wanted when I was testing the original TUI PR. These will probably be removed as soon as we do anything interesting with the UI, but they're nice for now.
=> Add key bindings in TUI mode

src/tui/mod.rs
=> TUI: Follow output when scrolled to the bottom

test-harness/src/checkpoint.rs, test-harness/src/ghciwatch.rs
This makes it easier to pass `CheckpointIndex`es around.
(`CheckpointIndex`es identify ranges of events in logs during tests, to assert that events were logged during particular ranges of time.)
=> `CheckpointIndex::into_index` -> `as_index`

test-harness/src/matcher/base_matcher.rs, test-harness/src/tracing_json.rs, tests/error_log.rs, tests/test.rs
This makes it easier to identify the correct span (e.g. `in_spans(["run_ghci", "initialize"])` would match an event with spans `["run_ghci", "stdout", "initialize"]`, but `in_leaf_spans` would not).
=> Support multiple spans in `BaseMatcher::in_leaf_span`

test-harness/src/ghciwatch.rs
In the test harness, we use methods like `assert_logged_in_checkpoint` and `assert_logged_or_wait` to find events in a checkpoint. These methods error when no matching event is found and when the matcher errors.
Matcher errors are important -- the `NegativeMatcher` will error if its contained matcher matches an event, so we need to:
1. Check every event in the checkpoint when using these methods, even if we find a matching event early.
2. Have a separate method that only errors if the matcher errors (to distinguish between "matching failed" and "no matching event was found") — this lets `assert_logged_or_wait` distinguish between a matcher error (which should be propagated) and a missing event (so that it can wait for an event to be logged).
=> Check all events in `logged_in_checkpoint`

src/ghci/mod.rs, src/ghci/parse/mod.rs, src/ghci/parse/module_set.rs, src/ghci/parse/show_paths.rs, src/ghci/parse/show_targets.rs, src/ghci/parse/target_kind.rs, src/ghci/stdin.rs, src/normal_path.rs, tests/eval.rs
Our favorite bug is back! We have a situation where `ghciwatch` loads all the modules at the start of the session, so they're all loaded:
```
ghci> :show targets
Foo
Bar
Baz
```
Then, an eval command in (for example) module `Foo` is executed. To start with, the module is added and explicitly interpreted:
```
ghci> :add *src/Foo.hs
```
Unfortunately, this always uses the module path (see [#171](https://github.com/MercuryTechnologies/ghciwatch/pull/171)), so if `ghciwatch` wasn't the one to load the module (e.g. it was loaded at the start of the session), the module path and module name will conflict and lead tot he dreaded "module is defined in multiple files".
See: [https://gitlab.haskell.org/ghc/ghc/-/issues/13254#note_525037](https://gitlab.haskell.org/ghc/ghc/-/issues/13254#note_525037) …
=> Fix "module defined in multiple files" with eval commands

Cargo.lock, Cargo.toml
Update version to 0.5.9 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.9

src/main.rs
This makes it easy for subprocesses (e.g. Haskell code that runs in `ghci`) to determine if it's running in a `ghciwatch` process.
=> Set IN_GHCIWATCH for subprocesses

Cargo.lock, Cargo.toml
Update version to 0.5.10 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.10

src/ghci/error_log.rs, src/ghci/stderr.rs, tests/error_log.rs
```
// TODO: Could this cause problems where we get an event and a final stderr line is only
// processed after we write the error log?
```
Turns out the answer is "yes"!
=> Fix a flaky error log test

Cargo.lock, Cargo.toml
Update version to 0.5.11 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.11

src/cli.rs, src/ghci/mod.rs
`--errors` -> `--error-file`
Moved `--no-interrupt-reloads` out of "Logging options" section of `--help`.
=> Rename some CLI flags

src/ghci/mod.rs, src/ghci/parse/module_set.rs, tests/eval.rs
In https://github.com/MercuryTechnologies/ghciwatch/pull/214, we had a situation where modules were loaded:
ghci> :show targets
Foo
Bar
Baz
And then an eval comment in (e.g.) `Foo` causes the module to be added and explicitly interpreted by path:
ghci> :add *src/Foo.hs
Then, we have `Foo` loaded by name (`Foo`) and by path (`src/Foo.hs`), which triggers the dreaded bug.
At the time I proposed this fix, correctly:
> I think we can fix this by keeping track of how each module is added to the session — as a path or as a module name — and then only using that form going forward.
I threaded some extra information to the `:show targets` parser to track if modules were listed as names or paths, **but then at the end of `Ghci::interpret_module` I would always insert the module into the target set …
=> Fix "module defined in multiple files" AGAIN!!!!

Cargo.lock, Cargo.toml
Update version to 0.5.12 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.12

Cargo.lock, Cargo.toml, clap-markdown/Cargo.toml, clap-markdown/LICENSE-APACHE, clap-markdown/LICENSE-MIT, clap-markdown/README.md, clap-markdown/examples/complex_app.md, clap-markdown/examples/complex_app.rs, clap-markdown/src/formatter.rs, clap-markdown/src/lib.rs, clap-markdown/tests/test_examples.rs
This will generate CLI documentation for ghciwatch's user manual.
See the rendered docs: https://github.com/MercuryTechnologies/ghciwatch/blob/rebeccat/dux-2305-cli-documentation/clap-markdown/examples/complex_app.md
=> Add vendored/forked clap-markdown

.github/workflows/release.yaml
Blocked on #249
Builds and publishes the user manual on GitHub Pages when releases are published.
=> Publish user manual on GitHub pages

docs/lifecycle-hooks.md, src/ghci/manager.rs, src/ghci/mod.rs
Fixes an inconsistency between after-startup and after-restart hooks
=> Run after-restart hooks before eval commands and test suites

docs/comment-evaluation.md, src/ghci/parse/eval.rs
Now `-- $>foo` is accepted as an eval comment in addition to `-- $> foo`.
=> Make eval comment parsing more consistent

Cargo.lock, Cargo.toml
Update version to 0.5.13 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.13

Cargo.lock, Cargo.toml
Update version to 0.5.14 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.14

.github/workflows/release.yaml
What if 👉👈 I had to cut like three releases 😜 to get the user manual published 🤯 because GitHub Actions doesn't have any tools to let you test your actions before you run them 😳 and we were both girls!??
=> Fix publishing the user manual on GitHub Pages

Cargo.lock, Cargo.toml
Update version to 0.5.15 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 0.5.15

Cargo.lock, Cargo.toml, nix/packages/ghciwatch.nix, src/cli.rs, src/main.rs
Generate and ship CLI completions for a few common shells.
=> Generate CLI completions

CONTRIBUTING.md, Cargo.lock, Cargo.toml, flake.nix, nix/packages/cargo-llvm-cov.nix, nix/packages/ghciwatch.nix
- Adds optional coverage reports for test runs via `cargo llvm-cov nextest`. 
- Also adds the `llvm-tools-preview` extension via Nix
=> Adding coverage reporting for tests

nix/packages/ghciwatch.nix, treefmt.toml
Adds a `treefmt.toml` for formatting Rust and Nix code
Next: CI checks for treefmt (but this requires refactoring the flake checks so it's a bigger diff)
=> Add treefmt

CONTRIBUTING.md, README.md, docs/SUMMARY.md, docs/cli.md, docs/faq.md, docs/introduction.md
This makes the README mostly identical to the "Introduction" page of the manual.
- README.md gains a badge linking to the user manual
- "Why Rust?" moved into CONTRIBUTING.md
- "Why reimplement ghcid?" and "Why not use watchexec?" moved into a new FAQ page in the manual
=> Cleanup README.md

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md
I don't think there's any way to validate these without merging them?
=> Add PR/issue templates

README.md, docs/introduction.md
- Clean up features list
- Also add a link to the CONTRIBUTING.md
=> README cleanup

Cargo.lock, Cargo.toml
Update version to 1.0.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 1.0.0

src/ghci/parse/show_paths.rs, src/ghci/parse/show_targets.rs, src/normal_path.rs
Previously, if `:show targets` displayed a path, we would attempt to join that path to each of the module search paths and to GHCi's working directory to find the file.
In reality, GHCi only checks such paths relative to its working directory. (Indeed, if you change the working directory with `:cd`, GHCi will unload all modules. [1])
Also, the logic for checking these paths was broken, considering that the search paths can be relative to the working directory, but we weren't properly joining these paths.
In the future, I'll write some tests that do `--after-startup-ghci ":cd ../"` and see how much of ghciwatch explodes.
[1]: https://gitlab.haskell.org/ghc/ghc/-/blob/077cb2e11fa81076e8c9c5f8dd3bdfa99c8aaf8d/compiler/GHC.hs#L1073-L1083
=> Fix `:show targets` / `:show paths` parsing logic

src/ghci/parse/eval.rs, src/ghci/parse/ghc_message/compilation_summary.rs, src/ghci/parse/ghc_message/module_import_cycle_diagnostic.rs, src/ghci/parse/lines.rs
This is useful for line-oriented parsers that may consume input with no trailing newline character. While this is a [violation of the POSIX spec][posix], VS Code [does it by default][vscode].
[posix]: https://stackoverflow.com/a/729795
[vscode]: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files
Split off from #297
=> [NFCI] Use `line_ending_or_eof` consistently in parsers

src/ghci/parse/ghc_message/cant_find_file_diagnostic.rs, src/ghci/parse/ghc_message/compilation_summary.rs, src/ghci/parse/ghc_message/compiling.rs, src/ghci/parse/ghc_message/generic_diagnostic.rs, src/ghci/parse/ghc_message/mod.rs, src/ghci/parse/ghc_message/no_location_info_diagnostic.rs
=> [NFCI] Unwrap `GhcMessage` in diagnostic parsers

src/tui/mod.rs
The code to follow logs had a bug where it'd increment the scroll offset regardless of how much of the screen was filled, so on startup it would start "following", pushing the logs up off the top.
This PR adds a second check to wait until the logs have filled the screen before auto-incrementing the scroll offset to follow.
---
I also tweaked the formatting of the key mapping `match`es to be more readable (IMO) and introduced a rudimentary debug status bar (hidden by default) which was essential for understanding this bug and fixing it.
I've found keeping debug info like this readily available to be a huge boon when working on my text editor project. I recommend keeping this in the code, at least while the TUI is in an experimental stage. But I'm also happy to remove if you'd rather not …
=> Fix incorrect auto-scroll/follow behavior in TUI

docs/SUMMARY.md, docs/integration/tasty.md, docs/tasty-integration.md
=> add tasty integration notes

src/watcher.rs
Provide a more helpful error message when a watched path does not exist. For example,
```console
$ ghciwatch --watch does-not-exist
```
**Before**
```
Error:   × Tasks failed:
│ • run_ghci: ghci event channel closed
│ • run_watcher: No such file or directory (os error 2)
```
**After**
```
Error:   × Tasks failed:
│ • run_ghci: ghci event channel closed
│ • run_watcher: Cannot watch path that doesn't exist: "/home/chris/Projects/tweag/ghciwatch/does-not-exist"
```
Partially resolves #312
=> Patch: Better error reporting when a watched path does not exist

.github/workflows/version.yaml, nix/packages/get-crate-version.nix
PR #329 failed to create a release because the release workflow ran in the context of the fork:
```
Run peter-evans/create-pull-request@v5
Error: Input 'token' not supplied. Unable to continue.
Restore git configuration
Error: Cannot read properties of undefined (reading 'removeAuth')
```
Change the workflow to run in `pull_request_target` to fix this, I hope.
Also update `get-crate-version` to not depend on any runtime tools, only the Nix expressions.
See: https://github.com/MercuryTechnologies/ghciwatch/actions/runs/12130981516/job/33822389311
=> Fix release workflow with PRs from forks

src/ghci/manager.rs, src/watcher.rs
This is clearer on its purpose: ghci itself does not generate these events, rather they are events to send to ghci.
=> GhciEvent: rename to WatcherEvent

Cargo.lock, Cargo.toml
Update version to 1.1.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 1.1.0

src/incremental_reader.rs, src/lib.rs
Wew. That was a bug.
The reproducer is here: https://github.com/rampion/ghciwatch-bug-demo
After tracing `consume_str`, I found out that the cause of our problems is that hspec includes the NL in their coloured output before resetting colour.
https://github.com/hspec/hspec/blob/fb9916f07e580f2572220d381e1886e765df95b7/hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs#L297-L306
That means that it is a pain in the ass to parse, since it shoves random ANSI escapes onto the next line. The easiest, and probably most correct, solution to this is to just eat ANSI escapes while looking for markers.
=> [DUX-3004]: handle evil clients that send ANSI escapes after NL

Cargo.lock, Cargo.toml
Update version to 1.1.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 1.1.1

Cargo.lock, Cargo.toml
Update version to 1.1.2 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 1.1.2

Cargo.lock, Cargo.toml
Update version to 1.1.3 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 1.1.3

flake.lock, flake.nix, nix/packages/checks/treefmt.nix, nix/packages/ghciwatch.nix, src/clap_markdown/formatter.rs, src/ghci/loaded_module.rs, src/ghci/mod.rs, src/ghci/stdin.rs, test-harness/Cargo.toml, test-harness/src/fs.rs, test-harness/src/ghciwatch.rs, test-harness/src/internal.rs, test-harness/src/tracing_json.rs
- Update `flake.lock` to update `nixpkgs` and other inputs
- Update Rust toolchain from 1.72.1 to 1.81.0
=> Update `flake.lock`, Rust toolchain, GHC

flake.nix, src/ghci/error_log.rs, src/ghci/parse/ghc_message/compilation_summary.rs, src/ghci/parse/ghc_message/mod.rs, src/ghci/parse/mod.rs, test-harness/src/ghc_version.rs, tests/error_log.rs
=> Support GHC 9.10, 9.12

Cargo.lock, Cargo.toml
Update version to 1.1.5 with [cargo-release](https://github.com/crate-ci/cargo-release).
=> Release version 1.1.5
