MercuryTechnologies/ghciwatch

Cargo.lock
Cargo.toml
src/cli.rs
src/ghci/mod.rs
src/main.rs
src/tracing/mod.rs

This will support testing infrastructure as well as debugging.

Add JSON logging

---

Cargo.lock
Cargo.toml
test-harness/Cargo.toml
test-harness/src/fs.rs
test-harness/src/lib.rs

These will help with writing tests

Add IO helpers for test harness

---

.config/nextest.toml
Cargo.lock
flake.lock
flake.nix
ghcid-ng/Cargo.toml
ghcid-ng/src/event_filter.rs
ghcid-ng/src/ghci/mod.rs
ghcid-ng/src/ghci/stderr.rs
ghcid-ng/src/ghci/stdin.rs
ghcid-ng/src/ghci/stdout.rs
ghcid-ng/src/incremental_reader.rs
ghcid-ng/src/watcher.rs
ghcid-ng/tests/basic.rs
ghcid-ng/tests/data/simple/simple.cabal
ghcid-ng/tests/data/simple/test/Main.hs
ghcid-ng/tests/data/simple/test/TestMain.hs
ghcid-ng/tests/error_log.rs
ghcid-ng/tests/test.rs
test-harness/src/fs.rs
test-harness/src/ghc_version.rs
test-harness/src/ghcid_ng.rs
test-harness/src/lib.rs

Add integration tests!!! The culmination of many PRs.

Add integration tests

---

ghcid-ng/src/ghci/mod.rs

This moves a bunch of logic into `Ghci::get_reload_actions`.

Split `Ghci::reload` up

---

.github/workflows/release.yaml

Oops
https://github.com/MercuryTechnologies/ghcid-ng/actions/runs/6279500723/job/17055314983

Fix `cargo release` build

---

test-harness/src/ghcid_ng.rs
test-harness/src/internal.rs

Housekeeping: Rename `GHC_PROCESS` to `GHCID_NG_PROCESS`

---

nix/ghcid-ng.nix
src/cli.rs
src/ghci/parse/ghc_message/position.rs
src/lib.rs
src/normal_path.rs
src/tracing/format.rs
test-harness-macro/src/lib.rs
test-harness/src/lib.rs

Also deny documentation warnings in CI

Housekeeping: Fix up documentation warnings

---

src/ghci/mod.rs

Extract `ghci` restart logic

---

src/maybe_async_command.rs

This prevents async shell hook output from being interleaved with ghci's output.

Capture async shell hook output

---

src/ghci/mod.rs

> is there a plan to add “All good!” to ghciwatch? the green text gives me dopamine

Add 'All good!' message when reloads finish

---

src/ghci/stdin.rs

If modules are already built, `--eval-commands` can fail because the module is `:add`ed but not interpreted. This explicitly interprets modules before evaluating commands in them. Unfortunately I wasn't able to get a regression test working.

Interpret modules before evaluating commands in them

---

Cargo.lock
Cargo.toml

See: https://github.com/uttarayan21/ansi-to-tui/pull/38

Update ansi-to-tui to fix TUI colors

---

src/buffers.rs
src/tui/mod.rs

`Tui` is renamed to `TuiState`, `Tui` is now a bundle of a `TerminalGuard` and `TuiState`. This makes the code nicer.

Refactor TUI

---

test-harness/src/lib.rs
test-harness/src/matcher/and_matcher.rs
test-harness/src/matcher/fused_matcher.rs
test-harness/src/matcher/negative_matcher.rs
test-harness/src/matcher/never_matcher.rs
test-harness/src/matcher/option_matcher.rs
test-harness/src/matcher/or_matcher.rs

Implement `Clone` for `Matcher`s and export them

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix
src/tui/mod.rs

Support Rust 1.72 (for real)

---

.github/workflows/release.yaml
flake.nix
nix/packages/ghciwatch.nix

~~Blocked on #250~~
Builds the mdBook user manual in Nix and uploads it to GitHub releases in a `.tar.xz`.

Publish user manual in GitHub releases

---

justfile
nix/packages/ghciwatch.nix

Documentation for various development commands

Add justfile

---

.gitignore
CONTRIBUTING.md
src/string_case.rs

- Adds a trivial test case to bump string_case.rs to 100% coverage
- Adds some info on how to get coverage information in VSCode

Adding trivial test case to bump string_case.rs to 100% coverage

---

src/normal_path.rs

- Adding a small test for normal_path.rs

Adding a small test for normal_path.rs

---

.envrc

[DUX-3005] add envrc

---

Cargo.toml

Resolves https://github.com/MercuryTechnologies/ghciwatch/issues/350

feat(patch): enable LTO and codegen-units = 1 optimizations
